# jekyll setting
incremental: true

# Site settings
title: 咸鱼的幻想乡
email: yuvv.th@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yuvv's Blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://yuvv.github.io/" # the base hostname & protocol for your site

timezone: Asia/Shanghai

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'


# Social account
# twitter:  username
weibo: 3147725543
github: Yuvv
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
#google_analytics: UA-86394520-3
google_analytics4: G-HFFY0P3VTB

# katex
katex: true

# Build settings
markdown: kramdown
kramdown:
  math_engine: katex
sass:
  style: compressed
plugins:
  - jekyll-sitemap
